### ISSUE TITLE
nio new is re-installing nio framework

### ISSUE THREAD

**Issue by shadetree01010100** [niolabs/nio-cli#100]
```
...
Collecting nio (from -r ./movidius/service_tests/requirements.txt (line 1))
Collecting jsonschema (from -r ./movidius/service_tests/requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting safepickle>=0.1.0 (from nio->-r ./movidius/service_tests/requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/80/70/0595f0cb6a129eb2cccd00c8a7e72cf48acb95302d67e56bc29f652bba60/safepickle-0.2.0-py3-none-any.whl
Installing collected packages: safepickle, nio, jsonschema
Successfully installed jsonschema-2.6.0 nio-3.0.0 safepickle-0.2.0
```
nio 3.0.0 and safepickle 0.2.0 were already installed.

**Comment by f1401martin** [comment]
Can't reproduce this on mac, fyi, in later versions of pip updating dependencies only when necessary is now the default behavior.

There are command line arguments one could use though, like `--upgrade-strategy only-if-needed`, but seem unnecessary considering it is the default behavior of pip's of late.

On mac I get: 
`Requirement already satisfied: nio in /usr/local/lib/python3.6/site-packages (from -r ./franky_project/service_tests/requirements.txt (line 1))`

@tyoungNIO could you verify this is happening with the latest version of pip...
