### ISSUE TITLE
Use pynio for nio api calls

### ISSUE THREAD

**Issue by vitiral** [niolabs/nio-cli#4]
@f1401martin will be able to say the most about this. What do you think about using the nioapi for the command line interface? It has a whole bunch of machinery, error checking, and other valueable features, and having one unified interfaces makes a lot of sense.

**Comment by hansmosh** [comment]
I think that is absolutely what we should do! The nioapi needs to be split out into it's own repository first. Right now I think it's still just a branch on nio-integration. 

@cloudformdesign Could you pull out your nioapi code and put it into its own repository. I think I mentioned this before, but I still believe it should be renamed to something like pynio. nioapi feels wrong to me for some reason.

**Comment by cloudformdesign** [comment]
**pynio** is a fine name for it. I mostly just came up with a name on the spot. Another option would be niorest

I think Randy is going to need the repository we put it into to be private. I will talk to him on Monday

**Comment by cloudformdesign** [comment]
Also, it is actually not difficult to use a branch of a repository as a submodule.

git submodule add -b nioapi gitpath path/to/folder

**Comment by f1401martin** [comment]
I agree, a few notes would help understanding how this api differentiates from the one used currently by the Services Builder, etc

**Comment by mattdodge** [comment]
Not currently supporting pynio, closing until we do
