### ISSUE TITLE
Use git:// for git dependent commmands

### ISSUE THREAD

**Issue by tlugger** [niolabs/nio-cli#60]
The nio-cli does not immedately work for git dependent commands such as `nio new` and `nio add` because these commands attempt to clone using `git@github.com:...`. Setting up ssh for a GitHub account fixes this issue but isn't ideal for something like a Raspberry Pi. Would it make sense for all `clone` commands within the cli to use `https://github.com/...`?

**Comment by mattdodge** [comment]
I think the default should actually be `git://`, using `https` or `git@` requires a GitHub account, which isn't necessarily an assumption I think we need to make.

Potentially helpful/relevant: https://gist.github.com/grawity/4392747

**Comment by tlugger** [comment]
Agreed! I didn't know about `git://` cloning. I can work on an update
